[package]
name = "cuda_d3d11_interop_bindings"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.61.1", default-features = false, features = [
    "Win32_Graphics_Direct3D11",
] }

[build-dependencies]
bindgen = "0.71.1"
